class NamingCodes {
	constructor() {
		this.industries = {
			FD: 'Food delivery',
			OO: 'Online ordering',
			OF: 'Ofline food',
			NO: 'Non-online ordering'
		}

		this.countries = {
			AR: 'Argentina',
			AU: 'Australia',
			AT: 'Austria',
			BH: 'Bahrain',
			BD: 'Bangladesh',
			BA: 'Bosnia and Herzegovina',
			BR: 'Brazil',
			BN: 'Brunei',
			BG: 'Bulgaria',
			CA: 'Canada',
			CL: 'Chile',
			CN: 'China',
			CO: 'Colombia',
			HR: 'Croatia',
			CY: 'Cyprus',
			CZ: 'Czech Republic',
			EC: 'Ecuador',
			EG: 'Egypt',
			FI: 'Finland',
			FR: 'France',
			GE: 'Georgia',
			DE: 'Germany',
			GR: 'Greece',
			HK: 'Hong Kong',
			HU: 'Hungary',
			IN: 'India',
			IT: 'Italy',
			JO: 'Jordan',
			KZ: 'Kazakhstan',
			KW: 'Kuwait',
			LB: 'Lebanon',
			MY: 'Malaysia',
			MX: 'Mexico',
			ME: 'Montenegro',
			NL: 'Netherlands',
			NO: 'Norway',
			OM: 'Oman',
			PK: 'Pakistan',
			PA: 'Panama',
			PY: 'Paraguay',
			PE: 'Peru',
			PH: 'Philippines',
			PL: 'Poland',
			PR: 'Puerto Rico',
			QA: 'Qatar',
			RO: 'Romania',
			SA: 'Saudi Arabia',
			RS: 'Serbia',
			SG: 'Singapore',
			SK: 'Slovakia',
			KR: 'Korea',
			ES: 'Spain',
			SE: 'Sweden',
			CH: 'Switzerland',
			TW: 'Taiwan',
			TH: 'Thailand',
			TR: 'Turkey',
			AE: 'United Arab Emirates',
			UK: 'United Kingdom',
			UY: 'Uruguay',
			VE: 'Venezuela'
		}

		this.brands = {
			BT: 'Baedaltong',
			EF: 'eFood',
			PO: 'PizzaOnline',
			PY: 'PedidosYa',
			YO: 'Yogiyo',
			CD: 'ClickDelivery',
			DJ: 'Damejidlo',
			YS: 'Yemeksepeti',
			LH: 'Lieferheld',
			PDE: 'Pizza.de',
			MJM: 'Mjam',
			OP: 'OnlinePizza',
			PPP: 'PizzaPortal',
			TB: 'Talabat',
			FOC: 'FoodOnClick',
			FA: 'Foodarena',
			FO: 'Foodora',

			DN: 'Donesi',
			FP: 'Foodpanda',
			HS: 'HungerStation',
			NP: 'Netpincer',
			HF: 'Hellofood',
			CG: 'Carriage',
			BM: 'BaeMin',
			DP: 'Domino pizza',
			PC: 'Pelicana Chicken',
			GM: 'GMarket',
			DB: 'DaBang',
			DC: 'DB Direct car insurance',
			EX: 'Expedia',
			'11': '11th Street',
			MC: 'McDonald',
			BR: 'Baskin Robbins',
			PB: 'Paris Baguette',
			LO: 'Lotteria',
			JU: 'Juicy',
			LHM: 'Lotte Hi-Mart',
			SB: 'Shinhan Bank',
			IL: 'iloom',
			KI: 'Kia New Sorento',
			KT: 'Kumho Tire',
			AZ: 'Amazon',
			TV: 'Trivago',
			EY: 'Ebay',
			NT: 'Netto',
			ED: 'Edeka',
			IK: 'Ikea',
			ST: 'Saturn',
			'24': 'Check 24',
			ZA: 'Zalando',
			DO: 'Domicilios',
			DR: 'Dr.Oetker',
			KN: 'Knorr',
			CA: 'C&A',
			MU: 'Müller',
			AX: 'Axe',
			WW: 'Weight Watchers',
			NU: 'Nutella',
			FL: 'Flaconi',
			SX: 'Mister Spex',
			AU: 'WIrkaufendeinauto',
			AL: 'Amorelie',
			AY: 'About you',
			MM: 'Media Markt',
			NV: 'Nivea',
			RB: 'Red Bull',
			DV: 'Dove',
			DE: 'Davivienda',
			PE: 'Pepsi CO',
			AG: 'Aguila',
			JV: 'Juan Valdez',
			FY: 'Frisby',
			ECH: 'El Corral Hamburgers',
			POP: 'Popsy',
			KFC: 'KFC',
			ER: 'Exito + Rappi',
			ML: 'Mercado Libre',
			LI: 'Linio',
			MQ: 'Merqueo',
			FB: 'Falabella',
			CY: 'Comeya/ifood',
			KK: 'Kokoriko',
			BB: 'BBVA',
			IB: 'Iberia',
			CC: 'Coca Cola',
			HNS: 'Head&Shoulders',
			PT: 'Postobon',
			CR: 'Careem',
			TL: 'Teletál',
			LY: "Lay's",
			DEC: 'Decathlon',
			ALZ: 'Alza',
			EXD: 'Extreme Digital',
			JF: 'Jófogás',
			TEL: 'Telenor',
			VE: 'Vision Express',
			TS: 'Tesco',
			DCH: 'Deichmann',
			DOP: 'Don Pepe',
			PF: 'Pizza Forte',
			MAG: 'eMAG'
		}

		this.channels = {
			TV: 'TV',
			YT: 'YouTube',
			PS: 'Paid Social'
		}
	}
}

export default NamingCodes
